/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "文档",
  "description": "总结",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "总结",
        "tagline": "记录",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-69c0ee05",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-10061e16",
      "path": "/about.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/contact.html",
      "relativePath": "contact.md",
      "key": "v-529680b6",
      "path": "/contact.html"
    },
    {
      "title": "ceshi",
      "frontmatter": {},
      "regularPath": "/css/one.html",
      "relativePath": "css/one.md",
      "key": "v-2d66e0ae",
      "path": "/css/one.html",
      "headers": [
        {
          "level": 2,
          "title": "ceshi",
          "slug": "ceshi-2"
        },
        {
          "level": 2,
          "title": "safdasd",
          "slug": "safdasd"
        }
      ]
    },
    {
      "title": "css常见问题",
      "frontmatter": {},
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-01a13a8a",
      "path": "/css/",
      "headers": [
        {
          "level": 2,
          "title": "图片文字的间距",
          "slug": "图片文字的间距"
        },
        {
          "level": 3,
          "title": "图片之间的空隙",
          "slug": "图片之间的空隙"
        },
        {
          "level": 2,
          "title": "margin",
          "slug": "margin"
        },
        {
          "level": 3,
          "title": "替换元素",
          "slug": "替换元素"
        },
        {
          "level": 3,
          "title": "无效的场景",
          "slug": "无效的场景"
        },
        {
          "level": 2,
          "title": "BFC",
          "slug": "bfc"
        },
        {
          "level": 2,
          "title": "关于 height:100%",
          "slug": "关于-height-100"
        },
        {
          "level": 3,
          "title": "为何 height:100%无效",
          "slug": "为何-height-100-无效"
        },
        {
          "level": 3,
          "title": "如何让元素支持 height:100%效果",
          "slug": "如何让元素支持-height-100-效果"
        },
        {
          "level": 2,
          "title": "vertical-align",
          "slug": "vertical-align"
        },
        {
          "level": 2,
          "title": "float",
          "slug": "float"
        },
        {
          "level": 2,
          "title": "1px问题",
          "slug": "_1px问题"
        },
        {
          "level": 3,
          "title": "像素比 dpi",
          "slug": "像素比-dpi"
        },
        {
          "level": 3,
          "title": "马赛克",
          "slug": "马赛克"
        },
        {
          "level": 3,
          "title": "手机像素显示问题",
          "slug": "手机像素显示问题"
        }
      ]
    },
    {
      "title": "ceshi",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-1236e218",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "ceshi",
          "slug": "ceshi-2"
        },
        {
          "level": 2,
          "title": "safdasd",
          "slug": "safdasd"
        }
      ]
    },
    {
      "title": "前端案例",
      "frontmatter": {},
      "regularPath": "/css/two.html",
      "relativePath": "css/two.md",
      "key": "v-1c1af92e",
      "path": "/css/two.html",
      "headers": [
        {
          "level": 2,
          "title": "创意特效",
          "slug": "创意特效"
        },
        {
          "level": 2,
          "title": "safdasd",
          "slug": "safdasd"
        }
      ]
    },
    {
      "title": "组件",
      "frontmatter": {},
      "regularPath": "/module/",
      "relativePath": "module/README.md",
      "key": "v-127057a8",
      "path": "/module/",
      "headers": [
        {
          "level": 2,
          "title": "组件的演变",
          "slug": "组件的演变"
        },
        {
          "level": 2,
          "title": "组件的定义",
          "slug": "组件的定义"
        },
        {
          "level": 3,
          "title": "什么是组件化",
          "slug": "什么是组件化"
        },
        {
          "level": 3,
          "title": "生活中的常见的组件模式",
          "slug": "生活中的常见的组件模式"
        },
        {
          "level": 2,
          "title": "常见的第三方UI组件",
          "slug": "常见的第三方ui组件"
        },
        {
          "level": 2,
          "title": "现在组件的现状",
          "slug": "现在组件的现状"
        },
        {
          "level": 2,
          "title": "常见的组件实现方式（以vue为例）",
          "slug": "常见的组件实现方式-以vue为例"
        },
        {
          "level": 3,
          "title": "Web Components  新的组件方式",
          "slug": "web-components-新的组件方式"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/module/one.html",
      "relativePath": "module/one.md",
      "key": "v-58b42409",
      "path": "/module/one.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/module/two.html",
      "relativePath": "module/two.md",
      "key": "v-6b92363d",
      "path": "/module/two.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "指南",
        "link": "/guide/"
      },
      {
        "text": "组件",
        "link": "/module/"
      },
      {
        "text": "css兼容问题",
        "link": "/css/"
      },
      {
        "text": "搜索",
        "link": "https://baidu.com"
      }
    ],
    "sidebar": {
      "/module/": [
        "",
        [
          "one",
          "one"
        ],
        [
          "two",
          "two"
        ]
      ],
      "/css/": [
        "",
        [
          "one",
          "图形效果"
        ],
        [
          "two",
          "趋势"
        ]
      ],
      "/bar/": [
        "",
        "three",
        "four"
      ],
      "/": [
        "",
        "contact",
        "about"
      ]
    }
  }
}