/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "文档",
  "description": "总结",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "总结",
        "tagline": "记录",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-b90603d6",
      "path": "/"
    },
    {
      "title": "ceshi",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-aae94bb0",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "ceshi",
          "slug": "ceshi-2"
        },
        {
          "level": 2,
          "title": "safdasd",
          "slug": "safdasd"
        }
      ]
    },
    {
      "title": "组件",
      "frontmatter": {},
      "regularPath": "/module/",
      "relativePath": "module/README.md",
      "key": "v-30f1e890",
      "path": "/module/",
      "headers": [
        {
          "level": 2,
          "title": "组件的演变",
          "slug": "组件的演变"
        },
        {
          "level": 2,
          "title": "组件的定义",
          "slug": "组件的定义"
        },
        {
          "level": 3,
          "title": "什么是组件化",
          "slug": "什么是组件化"
        },
        {
          "level": 3,
          "title": "生活中的常见的组件模式",
          "slug": "生活中的常见的组件模式"
        },
        {
          "level": 2,
          "title": "常见的第三方UI组件",
          "slug": "常见的第三方ui组件"
        },
        {
          "level": 2,
          "title": "现在组件的现状",
          "slug": "现在组件的现状"
        },
        {
          "level": 2,
          "title": "常见的组件实现方式（以vue为例）",
          "slug": "常见的组件实现方式-以vue为例"
        },
        {
          "level": 3,
          "title": "Web Components  新的组件方式",
          "slug": "web-components-新的组件方式"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/module/one.html",
      "relativePath": "module/one.md",
      "key": "v-f6090c0e",
      "path": "/module/one.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/module/two.html",
      "relativePath": "module/two.md",
      "key": "v-d04ce7a6",
      "path": "/module/two.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "指南",
        "link": "/guide/"
      },
      {
        "text": "组件",
        "link": "/module/"
      },
      {
        "text": "搜索",
        "link": "https://baidu.com"
      }
    ],
    "sidebar": {
      "/module/": [
        "",
        [
          "one",
          "123"
        ],
        [
          "two",
          "345"
        ]
      ],
      "/bar/": [
        "",
        "three",
        "four"
      ],
      "/": [
        "",
        "contact",
        "about"
      ]
    }
  }
}